### ISSUE TITLE
Update Avalonia

### ISSUE THREAD

**Issue by mausch** [AvaloniaUI/AvaloniaEdit#101]
Hi and thanks for all the hard work on this project!
It seems that this codebase is using Avalonia 0.9.0-preview1 ( https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/build.cake#L158 )
This is missing several bugfixes in later versions of Avalonia. Notably a [fix in 0.9.2](https://github.com/AvaloniaUI/Avalonia/pull/3453) which causes a hard crash at startup for ILSpy on NixOS .
I'm not familiar with this codebase or even Avalonia, is this as easy as changing that version in the Cake file? Would the tests catch any breaking changes (hopefully there are none)?

**Comment by danwalmsley** [comment]
updated.
