### ISSUE TITLE
AppendText doesn't update scroll area; Select all -> Delete doesn't either

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/AvaloniaEdit#105]
## Issue

Something in the text area isn't updating properly when using `AppendText` (or otherwise manipulating the text). I chatted with @danwalmsley in Discord about this, but we didn't get to the bottom of it. Basically, my app uses AvaloniaEdit as a console and appends text a bunch; however, the user can never see all the text that gets added because the scrollbar breaks and it appears as though there is nothing more to see. If you highlight/select the text, though, the UI updates nicely and you can view everything as you'd expect.

![avalonia-edit-bugs](https://user-images.githubusercontent.com/5092399/88591952-2fa90a80-d02b-11ea-9a0b-aaa37371999d.gif)

The fact that this is visible with the scrollbar may just be a red herring and not the actual issue.

## Repro 

This uses Avalonia CI build 8974, but you should be able to repro with 0.10.0-preview1 too.

https://github.com/Deadpikle/AvaloniaEdit/tree/bug/scrollbar

1. Start demo app
2. Click 'Append text test' a bunch, slowly. Watch the scrollbar not update.
3. Click in the text anywhere and select. The scroll area updates, as evidenced by the scrollbar.

or

1. Start demo app
2. Click 'Append text test' a bunch of times (fast or slow)
3. Control + A -> Delete key to remove all text
4. Scroll bar is still there and you can scroll with mouse wheel even though nothing is there

## Notes

In Discord, I reported that moving `TextView.SetScrollOffset`'s  `ScrollOffsetChanged` call outside of its `if` statement fixed things. **This was incorrect.** It does not fix things.

**Comment by Deadpikle** [comment]
Note: I don't think this was inherently broken in 0.10.0. My "other" branch (https://github.com/Deadpikle/AvaloniaEdit/tree/feature/self-needed-things), where I did a bunch of things that didn't need to get done that I've been using for a while (it was messy so I wanted to move back towards the original source code), works just fine on the same preview build of Avalonia.

**Comment by derekantrican** [comment]
Is there a workaround fix for this in 0.9.0-preview1? I am using `AppendText` a bunch and `ScrollToEnd`, `ScrollToVerticalOffset`, & `ScrollTo` don't seem to do anything (with the intention being "ScrollToEnd")
