### ISSUE TITLE
100% cpu usage on linux

### ISSUE THREAD

**Issue by Blquinn** [AvaloniaUI/AvaloniaEdit#111]
Hello, I'm experiencing 100% cpu usage when running the Demo on Linux. Also seeing the when I try to implement the editor in my application.

Using master branch @ 9c8b9feda42d72be6ec1e25c7fede67554af1ecd

uname -a
Linux ben-nix 5.4.58-1-MANJARO #1 SMP PREEMPT Tue Aug 11 15:46:30 UTC 2020 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/6005812/92308705-c5f71700-ef6d-11ea-913b-8149bd5bfcbf.png)

**Comment by Deadpikle** [comment]
Do you think this is fixed by https://github.com/AvaloniaUI/Avalonia/pull/4691 ?

**Comment by danwalmsley** [comment]
That's the Linux bug we just fixed will close and an update will be pushed shortly. Bug is in avalonia not avalonia edit.

**Comment by Blquinn** [comment]
Oops, yeah I didn't actually check to see if the bug goes away when I remove the edit component :/ Sorry!

Closing the ticket.
