### ISSUE TITLE
TextEditor throws an exception on startup

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/AvaloniaEdit#113]
On startup I get the following exception:

```
MissingMethodException: Method not found: 'Void Avalonia.Media.Pen..ctor(Avalonia.Media.IBrush, Double, Avalonia.Media.DashStyle, Avalonia.Media.PenLineCap, Avalonia.Media.PenLineCap, Avalonia.Media.PenLineCap, Avalonia.Media.PenLineJoin, Double)'.
```

My xaml only contains `<AvaloniaEdit:TextEditor/>`. I'm running Avalonia 0.9.12. Any suggestions?

**Comment by maxkatz6** [comment]
Do you use AvaloniaEdit 0.9.0-preview1 ? It is compatible with Avalonia 0.9.12.

**Comment by derekantrican** [comment]
Ah - that helps me at least get building! I don't normally use the prereleases.

Now I just have to figure out why it's not showing up in the window...

**Comment by maxkatz6** [comment]
@derekantrican 
Check demo project for 0.9 version tag, there is style that you need to include
https://github.com/AvaloniaUI/AvaloniaEdit/blob/0.9.0-preview1/src/AvaloniaEdit.Demo/App.xaml#L8

**Comment by derekantrican** [comment]
Perfect! `<StyleInclude Source="resm:AvaloniaEdit.AvaloniaEdit.xaml?assembly=AvaloniaEdit" />` was exactly what I was looking for. Thanks!
