### ISSUE TITLE
Does AvaloniaEdit support typing pictures？

### ISSUE THREAD

**Issue by Aaronlog** [AvaloniaUI/AvaloniaEdit#114]
Is there a text editing control that supports the input of images？

**Comment by HendrikMennen** [comment]
AvaloniaEdit does not support this afaik.
You can try to do it yourself. 
There is
```c#
Application.Current.Clipboard.GetDataAsync()
```
but you would have to find out how to convert that data to bitmap yourself.
I agree it would be nice to have a control like that but AvaloniaEdit is probably not made for this.
