### ISSUE TITLE
how to specify custom themes/color schemes?

### ISSUE THREAD

**Issue by redthing1** [AvaloniaUI/AvaloniaEdit#121]
how to specify custom themes/color schemes?

**Comment by danipen** [comment]
Now you can use Text mate built-in themes or you can write custom Text mate themes:
https://github.com/AvaloniaUI/AvaloniaEdit/blob/67e821102f5e39b2a4613ad7fc49968c64aabf25/src/AvaloniaEdit.TextMate/ThemeName.cs#L3
