### ISSUE TITLE
.Net 5 support

### ISSUE THREAD

**Issue by CarlosEX** [AvaloniaUI/AvaloniaEdit#122]
I'm developing in the Linux environment, I needed the RichTextBox and came across AvolonEdit. But it seems to me that it still doesn't provide support for .Net 5. According to the documentation: http://avalonedit.net/documentation/ . There is a forecast and whether it will be updated to support development?

**Comment by maxkatz6** [comment]
Have you tried it with .NET 5?
.NET 5 is compatible with libraries targeted netstandard, so everything should work.

**Comment by danwalmsley** [comment]
.net 5 is already supported.
