### ISSUE TITLE
Unable to resolve type TextEditor from namespace clr-namespace:AvaloniaEdit	

### ISSUE THREAD

**Issue by hopeko** [AvaloniaUI/AvaloniaEdit#123]
I new a AvaloniaMVVM project. Then installed Avalonia.AvaloniaEdit, directly used TextEditor in MainWindow.axaml, Visual Studio just showed an error, 'Unable to resolve type TextEditor from namespace clr-namespace:AvaloniaEdit'.
code
```cs
...
xmlns:avaloniaEdit="using:AvaloniaEdit"
...
<avaloniaEdit:TextEditor />
```

**Comment by JanTamis** [comment]
Use this as your xmlns: xmlns:AvalonEdit="clr-namespace:AvaloniaEdit;assembly=AvaloniaEdit"

**Comment by hopeko** [comment]
I have tried this before, same result.

**Comment by hopeko** [comment]
I have tried this earlier, same result.

**Comment by seljmov** [comment]
1) xmlns:avaloniaEdit= " usage:AvaloniaEdit"
2) xmlns:AvalonEdit= " clr - namespace:AvaloniaEdit"

These parameters cause me an error.
The full version helped solve the problem - xmlns:AvalonEdit= "clr-namespace:AvaloniaEdit;assembly=AvaloniaEdit"

**Comment by hopeko** [comment]
It works after I created a new project.

**Comment by hopeko** [comment]
No error after I recreated a new project. Just one problem, nothing shows up. 
```cs
  <Grid RowDefinitions="*" ColumnDefinitions="*">
    <avaloniaEdit:TextEditor Grid.Row="0" Grid.Column="0" Background="LightBlue" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />
  </Grid>
```
I give up. It's so difficult to use.

**Comment by maxkatz6** [comment]
@hopeko have you included AvaloniaEdit styles?
This line from example
https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/src/AvaloniaEdit.Demo/App.xaml#L7

**Comment by alexander-miglis** [comment]
It was not obvious that you needed to include the style. I had all the same issues as above. Everything started to work once the style line was added.
