### ISSUE TITLE
Context Menu does not show when editor is right clicked.

### ISSUE THREAD

**Issue by emmauss** [AvaloniaUI/AvaloniaEdit#128]
I'm unable to open the context menu  when I right click the editor. Context menu opens with a normal textbox, but not AvaloniaEdit

**Comment by chgauert** [comment]
add 2 lines to AvaloniaEdit/Editing/SelectionMouseHandler.cs
so right mouse button is not handled here - as the name implies it should handle left button

         private void TextArea_MouseLeftButtonDown(object sender, PointerPressedEventArgs e)
         {
+            if(e.GetCurrentPoint(TextArea).Properties.IsLeftButtonPressed == false)
+                return;

**Comment by danipen** [comment]
@Takoooooo is working on it here:
https://github.com/AvaloniaUI/AvaloniaEdit/pull/158

**Comment by Takoooooo** [comment]
should work correctly now
