### ISSUE TITLE
AvaloniaEdit works incorrectly with every value of AllowScrollBelowDocument

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/AvaloniaEdit#141]
How it works in Avalonia with the default value(true).
http://g.recordit.co/WMkRcE7Fxf.gif

How it works in WPF with value = true.
http://g.recordit.co/6h5W3Ea404.gif

How it works in Avalonia with value = false.
http://g.recordit.co/9KJGzvPYy9.gif

Fixed by #139 . Fixed behaviour https://recordit.co/8q2rA25T9I

How it works in WPF with value = false.
http://g.recordit.co/3SBqf65cD5.gif

**Comment by Takoooooo** [comment]
Ok I somewhy can't repro the behaviour in WPF with value = true from above. Current behaviour
https://recordit.co/DdFcAp3QS2 which matches well with our behaviour in Avalonia

**Comment by Takoooooo** [comment]
> Ok I somewhy can't repro anymore the behaviour in WPF with value = true from above. Current behaviour
> https://recordit.co/DdFcAp3QS2 which matches well with our behaviour in Avalonia

It's reproducible only when you scroll with your mouse, not scrollbar.I'm not sure we need to port this also. That behaviour is bad IMO

**Comment by Takoooooo** [comment]
> > Ok I somewhy can't repro anymore the behaviour in WPF with value = true from above. Current behaviour
> > https://recordit.co/DdFcAp3QS2 which matches well with our behaviour in Avalonia
> 
> It's reproducible only when you scroll with your mouse, not scrollbar.I'm not sure we need to port this also. That behaviour is bad IMO

So current plan is to port the behaviour from WPF and additionally to make it consistent between scrollbar and mouse scrolling

**Comment by danipen** [comment]
@Takoooooo, agree. 

Note that other editors (VSCode, Sublime), behaves in that way. They allow scrolling below document by default, and they behave in this way:

- When using Mouse/Scrollbar, the editor allows to place the last line in the first position (only one line, the last document line is visible in the viewport).
- When using the arrow keys (or Ctrl+END), the last line is placed in the last viewport line.

Demo: https://www.loom.com/share/aa99e5381fe34efbb2d22d4caa673c74
