### ISSUE TITLE
Modifying the default scroll viewer.

### ISSUE THREAD

**Issue by Abdesol** [AvaloniaUI/AvaloniaEdit#146]
Is there any way to modify the default scroll viewer of the Avalon text editor?
I had one idea that is adding the Avalon text editor as a child to a scroll viewer and setting my scroll viewer style.
It was effective and was working except, I can't scroll from the middle of the element(text editor), and also when I type, it is not scrolling based on where the caret is found.

**Comment by maxkatz6** [comment]
There is ScrollViewer inside of the template, that you can change with selectors. Or replace whole template with your scroll viewer (x:Name should be the same)
https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/src/AvaloniaEdit/TextEditor.xaml

**Comment by Abdesol** [comment]
Am I supposed to modify the source code or I can create my own style with the same name in my project?

**Comment by maxkatz6** [comment]
Either way is possible. 
You either can go by modifying template with selector ```<Style Selector="AvalonEdit|TextEditor">``` (in other words, copy and modify the code).
Or you can go by creating new style selector '''<Style Selector="AvalonEdit|TextEditor /template/ ScrollViewer#PART_ScrollViewer">``` and add setters to it, what you need.

More in here https://docs.avaloniaui.net/docs/styling/styles

**Comment by Abdesol** [comment]
Sorry. I am using the Avalonia port of  WPF control. And the above docs you provided is not working for me. I think it is because I am in WPF. So, do you have any alternative docs for WPF too?
Thanks.

**Comment by maxkatz6** [comment]
Oh, so you are using AvalonEdit for WPF? It's a wrong repo in this case.
Can't help with WPF version.

See https://github.com/icsharpcode/AvalonEdit

**Comment by Abdesol** [comment]
ohok.
anyway, Thanks.
