### ISSUE TITLE
TextEditor.ScrollTo commented?

### ISSUE THREAD

**Issue by MihaMarkic** [AvaloniaUI/AvaloniaEdit#149]
Why are `TextEditor.ScrollTo` methods commented?

**Comment by chgauert** [comment]
change vertical / horizontal to following lines and it should work - at least for me it does

if (ScrollViewer != null)
     ScrollViewer.Offset = new Vector(offset,ScrollViewer.Offset.Y);

if (ScrollViewer != null)
     ScrollViewer.Offset = new Vector(ScrollViewer.Offset.X,offset);
