### ISSUE TITLE
Scroll not synchronized

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/AvaloniaEdit#15]
Scrolling from the editor syncs with the scroll bar, but not the other way around.

There's also an issue when hitting Enter to add a new line (scroll gets out of sync with text).

![scroll](https://cloud.githubusercontent.com/assets/496737/25571555/96c015c0-2e39-11e7-94f0-b69fc6dfc322.gif)

**Comment by danwalmsley** [comment]
I will have to try and work out whats going on here, I thought id fixed it, in the scrolling pr looks like its come back.

**Comment by danwalmsley** [comment]
Fixed in #20
