### ISSUE TITLE
MissingMethodException 

### ISSUE THREAD

**Issue by Ferryry** [AvaloniaUI/AvaloniaEdit#150]
I tried using Avalonia to create my first GUI based F# Programs and I encountered this unresolvable issue:

>  System.MissingMethodException: "Method not found: 'Void Avalonia.IAvaloniaObject.SetValue(Avalonia.AvaloniaProperty`1<!!0>, !!0, Avalonia.Data.BindingPriority)'."

![error_code](https://user-images.githubusercontent.com/88947587/129961880-05a1698a-9828-4dd2-b09a-13060b87f441.JPG)

**Comment by maxkatz6** [comment]
Check AvaloniaEdit and Avalonia versions. Both should be latest (0.10.x) or the same older major (0.9.x)
