### ISSUE TITLE
Unicode characters do not display and caret is incorrectly positioned

### ISSUE THREAD

**Issue by Sanae6** [AvaloniaUI/AvaloniaEdit#164]
I noticed that Japanese characters and Emoji are not displaying correctly in AvaloniaEdit, but show up in a label just fine.
For testing, text in the string in the text editor is `🙈🙈🙈🙈🙈🙈🙈🙈 スッシ`
![Failed to display unicode characters](https://user-images.githubusercontent.com/32604996/143137667-067a53c9-6ef6-4bd3-8a39-553c024ea27a.png)
As a result of that, the caret is also not positioned to where I'd selected the end of the string.
![Incorrectly displayed caret](https://user-images.githubusercontent.com/32604996/143137985-f63ba10d-85d0-421a-9e49-e6e760c9d80d.png)

**Comment by danipen** [comment]
Fixed in latest version.
