### ISSUE TITLE
Wrong complete window position on Avalonia 0.10.11 and 0.10.12

### ISSUE THREAD

**Issue by alexeybut** [AvaloniaUI/AvaloniaEdit#194]
Complete window opens on a wrong position, it AvaloniaEdit built on Avalonia 0.10.11 or 0.10.12.
With 0.10.10 the position is correct.
Platform: MS Windows 10.
The attached picture illustrates the issue:

![popup-wrong-place](https://user-images.githubusercontent.com/8170797/151433087-f03bbd62-98dc-43ef-a2f5-5d6a1abcfc99.png)
.

**Comment by cordasfilip** [comment]
@danipen Is there a way to fix this with the current release?

**Comment by danipen** [comment]
@whistyun any ideas about how to fix in current release?

**Comment by cordasfilip** [comment]
@whistyun I even tried using preview
<PackageReference Include="Avalonia" Version="11.0.0-preview2" />
<PackageReference Include="Avalonia.AvaloniaEdit" Version="11.0.0-preview1" />
<PackageReference Include="Avalonia.Desktop" Version="11.0.0-preview2" /> 
not working

**Comment by whistyun** [comment]
I think AvaloniaEdit shows three types of windows: CompletionWindow, OverloadInsightWindow and IME window.
@cordasfilip Did you mean the IME window has a wrong position?

Only the position of the IME window is wrong in my environment.

**CompletionWindow:**  
![image](https://user-images.githubusercontent.com/13712028/201506115-cd46dde7-773c-4598-bce5-896707a93e74.png)  

**OverloadInsightWindow:**  
![image](https://user-images.githubusercontent.com/13712028/201506154-bfb29c5f-862b-43f1-bbf8-9ff77efd16f2.png)

**IME window(I turned on IME, and inputed "世界"):**  
![image](https://user-images.githubusercontent.com/13712028/201506780-759f9db6-3fa3-4165-ae76-e0f1f50f1b2e.png)

I try it on [a test project](https://github.com/whistyun/testcode-garage/tree/master/TestForAvaloniaEdit).

**Comment by cordasfilip** [comment]
@whistyun Strange it's working fine on the project you sent me thanks for help will investigate if any other library is I am using could be causing the issue.

**Comment by danipen** [comment]
@Gillibald do you think the IME issue is already fixed or needs a fix?

**Comment by whistyun** [comment]
@danipen I forget to compare preview1 and latest.
IME support seems to have been applied [after preview1 was released](https://github.com/AvaloniaUI/AvaloniaEdit/commit/48aadf00b9615197ab8fa0ab38353e86356d4291).

However, a window position is wrong when the scroll position is shifted.

**The scroll position is not shift (This behavior is expected)**  
![image](https://user-images.githubusercontent.com/13712028/201527677-8d69a1a9-9eae-49ab-96e5-c9b0bba93b08.png)

**The scroll position is shifted horizontal**
![image](https://user-images.githubusercontent.com/13712028/201528181-69aed2db-04d2-4a1f-9f61-8356830e6630.png)

**The scroll position is shifted vertical**  
![image](https://user-images.githubusercontent.com/13712028/201527763-e30852a6-b898-458d-a807-1763c6b36992.png)

**Comment by danipen** [comment]
@Gillibald maybe we need to take this into account for the IME implementation for Avalonia Edit.

**Comment by Gillibald** [comment]
This issue also happens with Avalonia's TextBox. I haven't found a solution yet.
