### ISSUE TITLE
Handle scrolling

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/AvaloniaEdit#2]
Most of the scrolling code is currently commented out since Avalonia doesn't have `IScrollInfo`. Possibly `ILogicalScrollable` could be made to work here.

Most of the code is in `TextView` (I deleted much of the scroll code, may need to copy again from AvalonEdit).

**Comment by danwalmsley** [comment]
@aelij I can try and port in the ILogicalScrollable code from AvalonStudio!

**Comment by danwalmsley** [comment]
For reference:
https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L495

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L613

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L827

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L934

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L955

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L708

https://github.com/VitalElement/AvalonStudio/blob/master/AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.cs#L470

**Comment by danwalmsley** [comment]
PR #6 implements this!
