### ISSUE TITLE
Some Wrongs behavior with Wordwrap

### ISSUE THREAD

**Issue by guilhermeolisi** [AvaloniaUI/AvaloniaEdit#205]
Hi,

I'm using AvaloniaEdit and I really like it. Thanks for this control, it's one of the controls that was important in my decision to choose Avalonia for my cross-platform project.

I think I have two issue using WordWrap:

1. When WordWrap=true doesn't work (see picture below), I think it's because Horizontal Scroll is enabled, so I need to set HorizontalScrollBarVisibility=Disabled in code behind when WrodWrap=true and set HorizontalScrollBarVisibility=Auto when WrodWrap=false to work fine.

![image](https://user-images.githubusercontent.com/25594740/153200262-67b06ff0-53e0-4543-a5a1-1955f03bac1d.png)

2. Another issue is that when wordwrap=true the line is wrapped and some parts of the line are still hidden and only one other part is shown below 

Wrapped line:
![image](https://user-images.githubusercontent.com/25594740/153200589-d92c0aa4-5f42-47dc-a2b9-df848408259c.png)

Full line:
![image](https://user-images.githubusercontent.com/25594740/153202303-a6abd643-6d99-4863-8ede-666922c75d2b.png)

thanks for your attention.

**Comment by danipen** [comment]
I took a quick look. It seems that TextWrapping is partially implemented via [TextLineImpl](https://github.com/AvaloniaUI/AvaloniaEdit/blob/c841c5ba4d6cb80a2d55b9c4f205c3d265c8253d/src/AvaloniaEdit/Text/TextLineImpl.cs#L33), but it just wraps existing text runs, but we still need to implement word wrapping at [TextLineRun](https://github.com/AvaloniaUI/AvaloniaEdit/blob/c841c5ba4d6cb80a2d55b9c4f205c3d265c8253d/src/AvaloniaEdit/Text/TextLineRun.cs#L178) level.

I'll try to take a look into it during the weekend.

**Comment by Gillibald** [comment]
In my opinion we should transition to using the TextFormatter and automatically get those missing features without reinventing the weel all the time. AvaloniaEdit did not follow AvalonEdit's implementation in that area because there was no TextFormatter when this fork came alive.

**Comment by danipen** [comment]
Yes. I agree we should move to use the new TextFormatter too.

@Gillibald are you guys planning to implement it in the short term?

Otherwise I can provide a quick fix for it (it's really easy to do) and later move to use the new stuff.
