### ISSUE TITLE
Tab sign change the position of line

### ISSUE THREAD

**Issue by guilhermeolisi** [AvaloniaUI/AvaloniaEdit#206]
Hi,

When ShowTabs=true a sign is shown in the text but the line is shifted to the right, so tab indentation line is shifted to right relative to white space indentation line. I tested in AvalonEdit (WPF) and the line with tab is not shifted. See figures below:

AvaloniaEdit, ShowTabs=false, ShowSpaces=false 
![image](https://user-images.githubusercontent.com/25594740/153209712-503fc0db-fd2a-4b92-be40-bb7516a055ba.png)

AvaloniaEdit, ShowTabs=true, ShowSpaces=true
![image](https://user-images.githubusercontent.com/25594740/153209558-2b7e571a-3229-47af-9ee7-da1a136fa9d4.png)

AvalonEdit
![image](https://user-images.githubusercontent.com/25594740/153205881-6f4e4d9b-c619-4f41-8dd4-55338febb21f.png)

thanks for your attention

**Comment by danipen** [comment]
@guilhermeolisi, fixed. Could you verify that #207 fixes the issue for you? Thanks!

**Comment by guilhermeolisi** [comment]
> @guilhermeolisi, fixed. Could you verify that #207 fixes the issue for you? Thanks!

Hi @danipen, how can i verify #207? Do I need to download the source code of the control and test it? Sorry, I'm not a professional developer and I'm not familiar with this

**Comment by danipen** [comment]
Yes you can clone the repository and reference it from your csproj instead of referencing the Avalonia nugets.

**Comment by danipen** [comment]
Alternatively ... maybe @Takoooooo may create a new release. I'm that case you'd only have to update the AvaloniaEdit version in you csproj.

**Comment by danipen** [comment]
Yes I saw. I'm not aware about how line wrapping is implemented in AvaloniaEdit, sorry. 

Let's see if someone else knows how to fix that issue.

**Comment by guilhermeolisi** [comment]
> Yes I saw. I'm not aware about how line wrapping is implemented in AvaloniaEdit, sorry.
> 
> Let's see if someone else knows how to fix that issue.

Thanks @danipen , i will wait then

**Comment by Gillibald** [comment]
As far as I remember WordWrap isn't implemented yet

**Comment by danipen** [comment]
@Gillibald wrapping is partially implemented. I will continue the conversation in #205
