### ISSUE TITLE
Highlighting doesn't work running in x86 runtime

### ISSUE THREAD

**Issue by guilhermeolisi** [AvaloniaUI/AvaloniaEdit#233]
Hi,

I am using the AvaloniaEdit with TextMate, when I compile and run it in x64 runtime it works normally, but when I compile and run in x86 runtime the Highlighting is not applied.

**Comment by danipen** [comment]
Humm, yes. It's possible that [onigwrap ](https://github.com/danipen/TextMateSharp/tree/master/onigwrap)(the native lib TextMateSharp uses) has only support for x64. I would need to be re-compiled to have support for both x86 and x64.

**Comment by danipen** [comment]
@guilhermeolisi I just published a new version of TextMateSharp [v1.0.37](https://www.nuget.org/packages/TextMateSharp/1.0.37) that **should support win-x86**, please test it and let me know if it works for you. Thanks.

**Comment by guilhermeolisi** [comment]
Hi, @danipen, I updated to v1.0.37 and the highlighting is applied correctly running on x86 runtime, but now the problem occurs when running in x64 runtime.

**Comment by danipen** [comment]
Weird. Are you trying x64 in a x64 machine?

**Comment by danipen** [comment]
Oh sorry, you were right. Itt was a typo in the x64 package, fixed in https://github.com/danipen/TextMateSharp/pull/23.

I generated [TextMateSharp v1.0.38](https://www.nuget.org/packages/TextMateSharp/1.0.38). Please could you try that and confirm if all is working fine for you? Thanks!

**Comment by guilhermeolisi** [comment]
it is working correctly in both runtime. Very thanks
