### ISSUE TITLE
Doesn't work on nightly

### ISSUE THREAD

**Issue by AsafMahlev** [AvaloniaUI/AvaloniaEdit#246]
When trying to use it on the nightly, I get the following error:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Input, Version=0.10.12.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.
```

I assume that is because of this change:
https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes
```
Avalonia.Animation, Avalonia.Input, Avalonia.Interactivity, Avalonia.Layout, Avalonia.Visuals and Avalonia.Styling assemblies were merged into a Avalonia.Base assembly. While API surface wasn't changed, it's still a binary breaking change, and third-party packages needs to be recompiled to work with a new version.
```

So this package needs to be recompiled with the new dependencies to work with it.
Maybe it's too soon since it's still a nightly, but the change will go to the main package at some point...

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/AvaloniaEdit/tree/dev

**Comment by AsafMahlev** [comment]
Is there any feed/builds for this, or should I get it manually?

**Comment by Gillibald** [comment]
A preview release is out on nuget
