### ISSUE TITLE
Syntax highlighting fails under mac

### ISSUE THREAD

**Issue by chenjing1294** [AvaloniaUI/AvaloniaEdit#268]
<img width="949" alt="截屏2022-10-10 上午11 40 19" src="https://user-images.githubusercontent.com/21185657/194796292-90b50cbd-84ec-41bb-be14-145545c20721.png">

**Comment by danipen** [comment]
It's working fine in my mac...
![image](https://user-images.githubusercontent.com/501613/194817569-76c08bf5-6575-4fa3-aed8-c7161e750f23.png)

What macOS version/architecture are you trying?

**Comment by chenjing1294** [comment]
> It's working fine in my mac... ![image](https://user-images.githubusercontent.com/501613/194817569-76c08bf5-6575-4fa3-aed8-c7161e750f23.png)
> 
> What macOS version/architecture are you trying?

macOS Monterey 12.6 / M1 Pro, 
After I recompiled oniguruma, put it in the running directory and it returned to normal. Does it not support M1?

**Comment by danipen** [comment]
> After I recompiled oniguruma, put it in the running directory and it returned to normal. Does it not support M1?

Not sure, maybe not.

@Gillibald is the syntax highlight working for you? Are you using M1? My macOS is an intel-based one, so I cannot check that.

@chenjing1294 just to double check ... the Oniguruma bindings are provided by TextMateSharp. So ... question: is the [TextMateSharp demo](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Demo) working for you? If the answer is no ... we would need to [re-build](https://github.com/danipen/TextMateSharp/tree/master/onigwrap) the [oniguruma bindings](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp/Internal/Oniguruma/Native/osx) with M1 support.

**Comment by chenjing1294** [comment]
> @chenjing1294 just to double check ... the Oniguruma bindings are provided by TextMateSharp. So ... question: is the [TextMateSharp demo](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Demo) working for you? If the answer is no ... we would need to [re-build](https://github.com/danipen/TextMateSharp/tree/master/onigwrap) the [oniguruma bindings](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp/Internal/Oniguruma/Native/osx) with M1 support.

[TextMateSharp demo](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Demo) didn't work for me until I recompiled oniguruma on M1.

**Comment by danipen** [comment]
Oh ok, so it seems we need a new build for the oniguruma bindings.

@chenjing1294 some help would be appreciated so if you generate a new version of the [onigwrap dylib](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp/Internal/Oniguruma/Native/osx) I can generate a new TextMateSharp nuget and fix the issue in AvaloniaEdit.

**Comment by danipen** [comment]
I generated a new version of the native onigwrap library with arm64 support, so now macOS M1 should be supported. 

I cannot test M1, so please, @chenjing1294 could you try to manually replace the native binary with [this one](https://github.com/danipen/TextMateSharp/blob/osx-universal-binaries/src/TextMateSharp/Internal/Oniguruma/Native/osx/libonigwrap.dylib), and check if it's working fine for M1 now? Thanks in advance!

**Comment by danipen** [comment]
@chenjing1294 did you have a chance to test it?

**Comment by chenjing1294** [comment]
> @chenjing1294 did you have a chance to test it?

I pulled the latest version of the master branch, the problem still exists.
<img width="967" alt="截屏2022-10-18 下午5 15 45" src="https://user-images.githubusercontent.com/21185657/196390031-667dae48-2c93-4433-8b02-aaa70102f523.png">

M1 Version:
[libonigwrap.dylib.zip](https://github.com/AvaloniaUI/AvaloniaEdit/files/9808812/libonigwrap.dylib.zip)

**Comment by chenjing1294** [comment]
> @chenjing1294 did you have a chance to test it?

Great, problem solved, thank you.😊
