### ISSUE TITLE
Does the sample work with nuget package?

### ISSUE THREAD

**Issue by cordasfilip** [AvaloniaUI/AvaloniaEdit#288]
I just tried to create a new app by copying the code from the sample repository and installing the nuget, but I am unable to figure out why it's not why nothing if getting displayed? Is there a specific version of Avalonia that needs to be installed or is there some working example? I even looked at RoslynPad source code but that isn't working as well can't really figure out how to use in a green field project?

**Comment by danipen** [comment]
You may need to add the needed styles in the same application:
https://github.com/AvaloniaUI/AvaloniaEdit/blob/286efecf2ed473c8a2880ebef9f6c06db7b2713d/src/AvaloniaEdit.Demo/App.xaml#L7

**Comment by cordasfilip** [comment]
@danipen I am an idiot, thanks
