### ISSUE TITLE
Feature request: add asciidoc language support

### ISSUE THREAD

**Issue by markushaslinger** [AvaloniaUI/AvaloniaEdit#290]
In addition to markdown it would be awesome to also support [asciidoctor](https://docs.asciidoctor.org/asciidoc/latest/).

As far as I can tell [there is a textmate grammar available](https://github.com/mattneub/AsciiDoc-TextMate-2.tmbundle/blob/master/Syntaxes/asciidoc.tmLanguage) which is [also used in a VS code extension](https://marketplace.visualstudio.com/items?itemName=juracy.asciidoc-textmate).

@danipen as far as I understand it that would require an update for TextMateSharp first - would be willing to try and help out with a PR if that's something you'd be interested in.

**Comment by danipen** [comment]
Yes. Contributing TexmateSharp with new langs is quite simple. It's just adding them here: 

https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Grammars/Resources/Grammars

And just setup the lang here:
https://github.com/danipen/TextMateSharp/blob/master/src/TextMateSharp.Grammars/GrammarNames.cs

**Comment by danipen** [comment]
If you create the PR I can generate a new TextmateSharp nuget and a new AvaloniaEdit version.

**Comment by danipen** [comment]
We'd need the grammar in Jason format.
Plist format is not supported yet in Textmatesharp...

**Comment by markushaslinger** [comment]
Thanks for the pointers, I'll clone and tinker. Will create a PR once I've got something.

**Comment by danipen** [comment]
Feel free to ask... I'll do my best to help.

**Comment by danipen** [comment]
Ready a new TextmateSharp version that supports asciidoc
https://www.nuget.org/packages/TextMateSharp/1.0.50

It would be valuable adding a PR upgrading the nugget version. Here: https://github.com/AvaloniaUI/AvaloniaEdit/blob/286efecf2ed473c8a2880ebef9f6c06db7b2713d/Directory.Build.props#L6


Additionally we should add an asciidoc sample to the demo app:
https://github.com/AvaloniaUI/AvaloniaEdit/tree/master/src/AvaloniaEdit.Demo/Resources/SampleFiles

**Comment by markushaslinger** [comment]
Thank you for updating the package.
I can create the PR with the sample here as well.

**Comment by markushaslinger** [comment]
PR #291 is in, but I can't sign the CLA, because their website seems to be broken 🤷‍♂️
No idea how long that will be stuck in limbo, if you want to you can take the code and PR yourself.

**Comment by danipen** [comment]
Yes I'll take it. Thanks for the contribution.

**Comment by markushaslinger** [comment]
All good now, my PR is ready, apparently just took a while
