### ISSUE TITLE
Support for `osx-arm64`

### ISSUE THREAD

**Issue by alexandrehtrb** [AvaloniaUI/AvaloniaEdit#294]
Hello,

Could AvaloniaEdit support `osx-arm64` runtime?
TextMateSharp seems to support arm64, so I think that AvaloniaEdit can support it too, if the version of TextMateSharp is at least [1.0.45](https://github.com/danipen/TextMateSharp/releases/tag/v1.0.45).

Related: https://github.com/danipen/TextMateSharp/issues/40

**Comment by alexandrehtrb** [comment]
The tag for `11.0.0-preview1` shows TextMateSharp version 1.0.43

https://github.com/AvaloniaUI/AvaloniaEdit/blob/d9155f3af66e98ec7173c299299fd3add6328c5c/Directory.Build.props#L6

**Comment by danipen** [comment]
Yes but feel free to use last changes on master. Can we generate new versions @Gillibald @danwalmsley ?

**Comment by Takoooooo** [comment]
> Yes but feel free to use last changes on master. Can we generate new versions @Gillibald @danwalmsley @Takoooooo ?

Will do today

**Comment by danipen** [comment]
Thanks!

**Comment by Takoooooo** [comment]
> The tag for `11.0.0-preview1` shows TextMateSharp version 1.0.43
> 
> https://github.com/AvaloniaUI/AvaloniaEdit/blob/d9155f3af66e98ec7173c299299fd3add6328c5c/Directory.Build.props#L6

New release is available on NuGet,feel free to test and reopen if issue is not fixed.
