### ISSUE TITLE
Finish CodeCompletion work

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/AvaloniaEdit#3]
* Investigate why popups appear black
* Handle focus changes from completion window

**Comment by danwalmsley** [comment]
@aelij I also have the black popup issue in AvalonStudio... if you do something that triggers a repaint the second time around they re-draw!

I was awaiting the new rendering stack in avalonia to come through, hoping it might fix this, as it has been introduced to avalonia recently! (It used to work!)
