### ISSUE TITLE
Asking for Wiki/doc/tutorial

### ISSUE THREAD

**Issue by Hamid1382** [AvaloniaUI/AvaloniaEdit#302]
Hi and tnx for your great project
its great but it has poor docs
I'm a intermediate programmer an I've just started a new project , an IDE.
I was looking for a way to create a controller which allows user to edit an stylized text.
I don't want to use AvaloniaEdit's code highlighter and I want to code it myself. 
As an IDE it should be flexible and extensible.
I don't know what to do.
Do I have to implement such controller or can I use AvaloniaEdit?
If it's better to implement myself, where I have to start ?
and Please provide some docs i couldn't find anything

**Comment by danipen** [comment]
Sorry at this moment there is no documentation for this project.
