### ISSUE TITLE
Textmate nuget package built with Debug mode

### ISSUE THREAD

**Issue by guilhermeolisi** [AvaloniaUI/AvaloniaEdit#304]
Hi, I'm using TextMate package from nuget in my project and when I run Windows App Certification Kit to publish to Windows store, I get a error message saying that your package's dll files were build in Debug mode. Would you publish a nuget package built with Release mode?

The version of nuget package is 0.10.12.2

**Comment by danipen** [comment]
Do you mean [this package ](https://www.nuget.org/packages/TextMateSharp/) ?

**Comment by danipen** [comment]
Or [this one](https://www.nuget.org/packages/AvaloniaEdit.TextMate) ?

**Comment by guilhermeolisi** [comment]
> 

I mean this package: [AvaloniaEdit.TextMate](https://www.nuget.org/packages/AvaloniaEdit.TextMate)

**Comment by danipen** [comment]
Ok. @Takoooooo please could you review if the Nugget generation uses Release mode?

**Comment by Gillibald** [comment]
I think there is a missing: `--configuration "Release"` for dotnet pack

**Comment by Takoooooo** [comment]
We have Release AvaloniaEdit 11.0.0-preview5 with the fix for this issue included,please test and verify if that fixes your issue

**Comment by guilhermeolisi** [comment]
> We have released AvaloniaEdit 11.0.0-preview5 with the fix for this issue included,please test and verify if that fixes your issue

Thanks for fixing this issue, but I'm using nuget package for avalonia 0.10.18 to publish in Windows store, so I can't verify if this modification (for Avalonia 11) Will receive error message from Windows App Certification Kit
