### ISSUE TITLE
the editor is not displayed

### ISSUE THREAD

**Issue by bouyeijiang** [AvaloniaUI/AvaloniaEdit#327]
Avalonia 11.0.0-preview6

axaml code :
<UserControl x:Class="UNIONUI.Views.MainView"
			 xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			  xmlns:AvalonEdit="clr-namespace:AvaloniaEdit;assembly=AvaloniaEdit"
             xmlns:dm="using:Dock.Model.Core"
             xmlns:dmc="using:Dock.Model.Controls"
			 xmlns:vm="using:UNIONUI.ViewModels"
			 mc:Ignorable="d"
			 d:DesignWidth="1000" d:DesignHeight="550"
			   x:DataType="vm:MainWindowViewModel" x:CompileBindings="True">

	<Design.DataContext>
		<vm:MainWindowViewModel />
	</Design.DataContext>
	<UserControl.Resources>
		<StreamGeometry x:Key="DarkTheme">M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10Zm0-2V4a8 8 0 1 1 0 16Z</StreamGeometry>
	</UserControl.Resources>

	<Grid RowDefinitions="Auto" ColumnDefinitions="Auto,*">

		<Panel  Grid.Row="0" Grid.Column="0"  Grid.ColumnSpan="2">
			<AvalonEdit:TextEditor Name="Editor"
						 FontFamily="Cascadia Code,Consolas,Menlo,Monospace"
						 Margin="30"
						 HorizontalScrollBarVisibility="Auto"
						 VerticalScrollBarVisibility="Visible"
						 FontWeight="Light"
						 FontSize="14" />
		</Panel>

**Comment by danipen** [comment]
Did you add the needed style include?

https://github.com/AvaloniaUI/AvaloniaEdit/blob/daf432017f31da3f6182e5993b85d80bfc30c3b1/src/AvaloniaEdit.Demo/App.xaml#L8

**Comment by bouyeijiang** [comment]
i see...

**Comment by bouyeijiang** [comment]
by the way, Do not allow adding to user controls?Some errors occurred after adding:
 Attributes aren't allowed on element properties

**Comment by MathiasLui** [comment]
Oh... good that you had the same problem, because I didn't read the "StyleInclude" part in the "Getting Started" guide because it wasn't included in the code sample..

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的
