### ISSUE TITLE
Editor Style not found?

### ISSUE THREAD

**Issue by MaxDeBy** [AvaloniaUI/AvaloniaEdit#329]
I'm trying to add the Style for the Editor as it's done in the Demo, but I'm getting this error.

![image](https://user-images.githubusercontent.com/68479683/232864944-707c4698-a8b9-435a-9c63-8d539511a866.png)

Can someone tell me what I'm doing wrong?

**Comment by danipen** [comment]
Which avalonia version are you using? Ser details about how to add the style in the readme... https://github.com/AvaloniaUI/AvaloniaEdit#how-to-set-up-a-new-project-that-displays-an-avaloniaedit-editor

**Comment by danipen** [comment]
> If you're using 0.10.x.y based versions, include <StyleInclude Source="avares://AvaloniaEdit/AvaloniaEdit.xaml" />

**Comment by MaxDeBy** [comment]
Ah. I guess the Demo is not for Version 0.10 then. I just took "You can see the [Demo Application](https://github.com/AvaloniaUI/AvaloniaEdit/tree/master/src/AvaloniaEdit.Demo) as a reference." at face value.

Thanks for your help.
