### ISSUE TITLE
Unicode chars disappear sometimes

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/AvaloniaEdit#331]
Sometimes, unicode chars are not visible in AvaloniaEdit:

* Commenting the row containing unicode chars, make them disappear.
* Toggling the "view tabs" option, cause the unicode chars to appear/disappear.
![unicode (1)](https://user-images.githubusercontent.com/501613/233339042-5c3051ba-d6ea-4ab2-b84f-9d53e49aeb1c.gif)

**Comment by danipen** [comment]
It seems that is adding a tab what causes the issue:
![tab](https://user-images.githubusercontent.com/501613/234306078-a1596697-49e2-4178-b03c-bb34933979a8.gif)

**Comment by danipen** [comment]
Also, note that it still happens in `preview 7`.

**Comment by Gillibald** [comment]
Fixed by: https://github.com/AvaloniaUI/Avalonia/pull/11066
