### ISSUE TITLE
[v11rc1] Control keys bindings don't work

### ISSUE THREAD

**Issue by hypeartist** [AvaloniaUI/AvaloniaEdit#336]
AvaloniaEdit key bindings look kinda broken on 11rc1. Control keys handling doesn't work. Here's what I got when I hit 'Backspace' key in AvaloniaEdit.Demo app - `Handled = false`. While in 11p8 it's ok (`Handled = true`).
![image](https://github.com/AvaloniaUI/AvaloniaEdit/assets/3519388/2d60ea0b-c7af-4b80-b1c5-0c4351d2bbe6)

After some digging, it appears that in v11rc1 currently focused element is being reported wrong. 
In the method `RoutedCommand::CanExecute` the newly introduced static field `_inputElement` is set to `Border` (the deepest ancestor element of `TextEditor`) which, obviously, is not suited to serve the event of hitting `Backspace` key in the editor. While in the version v11p8 focused element is obtained via `Application.Current.FocusManager.Current` that contains the correct element - `TextEditor`

**Comment by chenjing1294** [comment]
`SearchCommands.FindPrevious`, `SearchCommands.FindNext`, `SearchCommands.CloseSearchPanel` also not work
![2023-06-03-15-59-22](https://github.com/AvaloniaUI/AvaloniaEdit/assets/21185657/d29eae80-6fa7-4164-8bbc-ab83277fa47d)
