### ISSUE TITLE
Pasting into the search bar with Ctrl+V pastes into the text editor

### ISSUE THREAD

**Issue by ArchLeaders** [AvaloniaUI/AvaloniaEdit#339]
When using `Ctrl+V` to paste into the search bar (while focused), the contents are instead pasted into the underlying text editor.

I tested this on `11-preview6` and `11-rc1.1`.

https://github.com/AvaloniaUI/AvaloniaEdit/assets/80713508/e7e7aa32-1c6c-4af3-be54-f6212eeda04a

**Comment by Gillibald** [comment]
Might be fixed by: https://github.com/AvaloniaUI/AvaloniaEdit/pull/337

**Comment by danipen** [comment]
@ArchLeaders please can you confirm?

**Comment by ArchLeaders** [comment]
Seems to be fixed, thanks guys!

**Comment by ArchLeaders** [comment]
**Edit:** I'm not entirely certain it is, I decided to also test against the mainstream from NuGet and it also works fine.

Either way it's more likely something in my code messing it up, so I'll have a look there before re-opening.
