### ISSUE TITLE
How to wrap? The 'enter' key does not work

### ISSUE THREAD

**Issue by BoyFaceGirl** [AvaloniaUI/AvaloniaEdit#347]
the 'backspace ' key cannot go back to delete

**Comment by cyraid** [comment]
It may be because of the new preview version of avalonia? I found that backspace doesn't work. Neither does arrow keys or enter.
@Gillibald Does AvaloniaEdit work fine for you with Avalonia 11.0.0-rc1.1?

**Comment by alexandrehtrb** [comment]
I came here to post this problem. I am trying the new 11.0.0-rc1.1 version, and Enter, Delete and Backspace do not work...

**Comment by alexandrehtrb** [comment]
I checked the `master` and the `release/11.0.0-rc1.1` branches and the problem only appears in the 11.0.0-rc1.1, I think it was already solved and the next release will fix it

**Comment by BoyFaceGirl** [comment]
> 
my Avalonia  of version is 11.0.0-rc1.1

![image](https://github.com/AvaloniaUI/AvaloniaEdit/assets/8773178/be1716f9-1396-4c08-aa17-efb660598150)

If the next version has been fixed, this issue can be closed

**Comment by Numpsy** [comment]
> I checked the `master` and the `release/11.0.0-rc1.1` branches and the problem only appears in the 11.0.0-rc1.1, I think it was already solved and the next release will fix it

Same issue as https://github.com/AvaloniaUI/AvaloniaEdit/issues/336 ?

**Comment by danipen** [comment]
I think so.

**Comment by cyraid** [comment]
> Did you checked the `master`?

No, I just use the nuget package. Are they going to release the fix on nuget? Or do I have to checkout the source for it? (And add it to my csproj and remember to update it etc)

**Comment by danipen** [comment]
@Takoooooo are you going to release?

**Comment by alexandrehtrb** [comment]
Avalonia release 11.0.0-rc2 was just published, can you guys publish a new release of AvaloniaEdit that includes this fix?

**Comment by Numpsy** [comment]
I had a quick go at building it with 11.0.0-rc2.2, and it looks like the build has been broken by the changes in https://github.com/AvaloniaUI/Avalonia/pull/11848 - and I haven't had time to try to do a PR to update that myself.

**Comment by Gillibald** [comment]
I will update AvaloniaEdit shortly

**Comment by danipen** [comment]
Can we close this?

**Comment by Gillibald** [comment]
Yep
