### ISSUE TITLE
NullReferenceException on losing focus

### ISSUE THREAD

**Issue by IvaYan** [AvaloniaUI/AvaloniaEdit#359]
Hello! I found a bug in the editor.

Reproduce:

1. Start AvaloniaEdit.Demo application.
2. Select some text in the editor (e.g. with a double click on a word)
3. Click on any button in the toolbar.
4. The application will crash.

Call stack:
```C#
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaEdit.Editing.TextArea.TextAreaTextInputMethodClient.get_Selection() in /Users/ivan/Downloads/AvaloniaEdit-master/src/AvaloniaEdit/Editing/TextArea.cs:line 1195
   at Avalonia.Native.AvaloniaNativeTextInputMethod.OnSurroundingTextChanged(Object sender, EventArgs e) in /_/src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs:line 100
   at Avalonia.Input.TextInput.TextInputMethodClient.RaiseSurroundingTextChanged() in /_/src/Avalonia.Base/Input/TextInput/TextInputMethodClient.cs:line 75

```

The reason is at `AvaloniaNativeTextInputMethod.OnSurroundingTextChanged`:

```C#
private void OnSurroundingTextChanged(object? sender, EventArgs e)
{
    if (_client == null)
    {
        return;
    }
    
    var surroundingText = _client.SurroundingText;
    var selection = _client.Selection; // < --- !

    _inputMethod.SetSurroundingText(
        surroundingText ?? "",
        selection.Start,
        selection.End
    );
}
```

The getter for `_client.Selection` looks like this:
```C#
get => new TextSelection(_textArea.Caret.Position.Column, _textArea.Caret.Position.Column + _textArea.Selection.Length);
```

and `_textArea` is null. That, in turn, is because of the method 
```C#
protected override void OnLostFocus(RoutedEventArgs e)
{
    base.OnLostFocus(e);

    Caret.Hide();

    _imClient.SetTextArea(null);
}
```
of class `TextArea`. As you can see, it calls `_imClient.SetTextArea(null)` and `SetTextArea` in turn calls `RaiseSurroundingTextChanged` that invokes the event that is handled by `AvaloniaNativeTextInputMethod.OnSurroundingTextChanged`. So at the moment of event, TextARea is null and thus getting its caret position fails.

**Comment by danipen** [comment]
@Takoooooo

**Comment by Takoooooo** [comment]
I guess the next AvaloniaEdit version will be released with the new version of avalonia,from what i know it should happen soon. But if this issue will be a problem to a lot of people i will release ASAP
