### ISSUE TITLE
style include on readme is out of date

### ISSUE THREAD

**Issue by redthing1** [AvaloniaUI/AvaloniaEdit#361]
The sample uses this: https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/src/AvaloniaEdit.Demo/App.xaml#L7C5-L7C84
Readme says this: https://github.com/AvaloniaUI/AvaloniaEdit#how-to-set-up-a-new-project-that-displays-an-avaloniaedit-editor

**Comment by danipen** [comment]
The demo uses the same style include the readme uses. Note that you need to use this part for v11.

> If you're 11.x.y based versions, include <StyleInclude Source="avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml" />
