### ISSUE TITLE
SnippetReplaceableTextElement - CreateGeometry is not null guarded

### ISSUE THREAD

**Issue by KrzysztofDusko** [AvaloniaUI/AvaloniaEdit#377]
Hello, I noticed that in SnippetReplaceableTextElement are two places win this type of usage

https://github.com/AvaloniaUI/AvaloniaEdit/blob/2a07c6ea07ddce749b85b902ffff02aa7f7e1276/src/AvaloniaEdit/Snippets/SnippetReplaceableTextElement.cs#L205

allready in some othere places null check exists.
https://github.com/AvaloniaUI/AvaloniaEdit/blob/2a07c6ea07ddce749b85b902ffff02aa7f7e1276/src/AvaloniaEdit/Rendering/TextView.cs#L1271

https://github.com/AvaloniaUI/AvaloniaEdit/blob/2a07c6ea07ddce749b85b902ffff02aa7f7e1276/src/AvaloniaEdit/Rendering/TextView.cs#L1272

Can we add null check to geometry in SnippetReplaceableTextElement as well ? 
**EDIT -** this situation causing null reference exception in some situations where part of snippet is not visible on screen

**Comment by KrzysztofDusko** [comment]
@danipen can i create pull request with fix?

**Comment by danipen** [comment]
sure!
