### ISSUE TITLE
Autocompletition is not working properly

### ISSUE THREAD

**Issue by KrzysztofDusko** [AvaloniaUI/AvaloniaEdit#407]
Problem is caused by (i dont fully understand why)
https://github.com/AvaloniaUI/Avalonia/pull/15035  -> 11.2.999-cibuild0046415-alpha

To reproceduce
With default Avalonia version (or 11.1.-beta1 or any before 11.2.999-cibuild0046415-alpha)
1. a.item2 (ignre font color problem)
![image](https://github.com/AvaloniaUI/AvaloniaEdit/assets/69449360/1834bdcc-77f5-4136-9022-cfc8b4e792a1)

2. use backspace
before https://github.com/AvaloniaUI/Avalonia/pull/15035 - **OK**
![image](https://github.com/AvaloniaUI/AvaloniaEdit/assets/69449360/9ec57c97-f521-4242-8f75-b122f8e52dd6)
after https://github.com/AvaloniaUI/Avalonia/pull/15035 - **NOT OK**
![image](https://github.com/AvaloniaUI/AvaloniaEdit/assets/69449360/6fa002e2-1e9a-47b9-89d9-fb831c75c8b7)

to force change Avalonia version you can use this
```xml
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.999-cibuild0046415-alpha" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.999-cibuild0046415-alpha" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.999-cibuild0046415-alpha" />
    <ProjectReference Include="..\AvaloniaEdit\AvaloniaEdit.csproj" />
    <ProjectReference Include="..\AvaloniaEdit.TextMate\AvaloniaEdit.TextMate.csproj" />
  </ItemGroup>
```

**Comment by TomEdwardsEnscape** [comment]
I can't follow these repro steps. What am I supposed to do at step 1? Type `a.Item2`? Find it in a file somewhere and press a key combination?

**Comment by KrzysztofDusko** [comment]
1. type a. item2 mark by mark
2. delete "m" by backspace
at this ponit full autocompelte list **should be visble** (item1, item2, item3 etc.) - 
 https://github.com/AvaloniaUI/Avalonia/pull/15035 is preventing tooltip (with autocoplete list) to show (visible at last screen)

If it's still not clear i can provide video.

**Comment by KrzysztofDusko** [comment]
Bad - neweset Avalonia
https://github.com/AvaloniaUI/AvaloniaEdit/assets/69449360/9357b2fc-bc09-4eff-8a98-b668b1c09e40
Good - Avalonia before 11.2.999-cibuild0046415-alpha
https://github.com/AvaloniaUI/AvaloniaEdit/assets/69449360/16ce9751-18ce-4396-9ae6-9805a21d5880

**Comment by KrzysztofDusko** [comment]
I can confirm with https://github.com/AvaloniaUI/Avalonia/pull/15177 issue do not occurs. Thanks !!
