### ISSUE TITLE
Could not load file or assembly 'Avalonia.Skia.Desktop

### ISSUE THREAD

**Issue by yellow18** [AvaloniaUI/AvaloniaEdit#42]
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Avalonia.Skia.Desktop, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Avalonia.AppBuilder.UsePlatformDetect()
   at AvaloniaEdit.Demo.Program.Main(String[] args) in Avalon\AvaloniaEdit-master\src\AvaloniaEdit.Demo\Program.cs:line 14

**Comment by danwalmsley** [comment]
@yellow18 are you running on windows or Linux?

**Comment by yellow18** [comment]
windows 10. visual studio 2017

**Comment by danwalmsley** [comment]
I believe this should be fixed now, sorry for the long delay.
