### ISSUE TITLE
CustomMargin renders incorrectly when scrolling

### ISSUE THREAD

**Issue by xanthome** [AvaloniaUI/AvaloniaEdit#442]
https://github.com/AvaloniaUI/AvaloniaEdit/blob/934f022406334b95813ecb9040b9e8864b81e1ac/src/AvaloniaEdit.Demo/CustomMargin.cs#L115

is fixed with:
`double y = visualLine.VisualTop - TextView.VerticalOffset + visualLine.Height / 2;`

<img width="437" alt="clicked-line10-no-scroll" src="https://github.com/user-attachments/assets/be30c014-e893-4666-8b20-33b13bd5ba57">
<img width="437" alt="clicked-line10-scrolled-down" src="https://github.com/user-attachments/assets/dc143da2-a030-42d8-ac13-affd1d9b9262">
<img width="511" alt="clicked-line10-scrolled-down-fixed" src="https://github.com/user-attachments/assets/3da3c609-a21d-4e37-a935-9121d3f46a32">

**Comment by danipen** [comment]
cc @mgarstenauer can you please check this?

**Comment by danipen** [comment]
I was able to open a new PR for this. Please @mgarstenauer take a look if you can. Thanks!
