### ISSUE TITLE
Control rendering glitch

### ISSUE THREAD

**Issue by PurpleGray** [AvaloniaUI/AvaloniaEdit#45]
Hello.

If I move applications window which contains AvaloniaEdit control to my second monitor with different resolution, control starts to expand (every second rendered control is start to get larger and larger, like if you use windows magnifier). You can reproduce it by using AvaloniaEdit.Demo application, or sample from attachments (it is the same demo actually).
At start:
![At start it was](https://user-images.githubusercontent.com/21021184/36427472-528d46e4-165e-11e8-8228-807ea6dee48d.png)
When I move it to another monitor:
![But then](https://user-images.githubusercontent.com/21021184/36427485-5f512c6a-165e-11e8-8638-271a4b38f57a.png)
[AvaloniaApplication2.zip](https://github.com/AvaloniaUI/AvaloniaEdit/files/1740262/AvaloniaApplication2.zip)

**Comment by danwalmsley** [comment]
This looks like an avalonia issue @kekekeks @grokys

**Comment by Stratocast3r** [comment]
May be, but may be not. I tested Avalonia's ControlCatalog sample and did not encounter such behaviour.

**Comment by latop2604** [comment]
I encounter the same issue on a mac. The window's content progressively zoom in when I move mouse in it.

**Comment by aelij** [comment]
Can you check if this still happens with latest version from master? I've updated it to the latest Avalonia.

**Comment by aelij** [comment]
Please reopen if this issue still occurs on latest version from master
