### ISSUE TITLE
Static resource 'ControlContentThemeFontSize' not found

### ISSUE THREAD

**Issue by timorj** [AvaloniaUI/AvaloniaEdit#471]
Hi, I met a problem, here is my decription:
 - I added avaloniaEdit in my project.
![image](https://github.com/user-attachments/assets/8eb82b1e-a3f9-47e5-8794-c7a1f80a4fa3)
- also added style in app.axaml. 
```
	<Application.Styles>
		<StyleInclude Source="avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml" />
		<semi:SemiTheme Locale="en-US" />
	</Application.Styles>
```
- and i use usercontrol in my view like this:
```
			<AvalonEdit:TextEditor Name="Editor"
							  FontFamily="Cascadia Code,Consolas,Menlo,Monospace"
							  Margin="30"
							  HorizontalScrollBarVisibility="Auto"
							  VerticalScrollBarVisibility="Visible"
							  FontWeight="Light"
							  FontSize="14"
						 
							 />
```
- but when i started this application, i got a crash by:
![image](https://github.com/user-attachments/assets/3a331748-f3c0-4f46-9f54-8a393fc176b7)

- I dont know why, I 've  confused by this for several days. Thanks

**Comment by NeverMorewd** [comment]
Same issue

**Comment by EgorVictor** [comment]
I had the same problem, which I currently solved by adding the following under App.axaml->Application.Resources
<x:Double x:Key=“ControlContentThemeFontSize”>12</x:Double
<FontFamily x:Key=“ContentControlThemeFontFamily”>Consolas</FontFamily>

**Comment by EgorVictor** [comment]
I had the same problem, which I currently solved by adding the following under App.axaml->Application.Resources
<x:Double x:Key="ControlContentThemeFontSize">12</x:Double>
<FontFamily x:Key="ContentControlThemeFontFamily">Microsoft YaHei</FontFamily>

**Comment by EgorVictor** [comment]
App.axaml->Application.Resources
`<x:Double x:Key="ControlContentThemeFontSize">12</x:Double>`
`<FontFamily x:Key="ContentControlThemeFontFamily">Microsoft YaHei</FontFamily>`

**Comment by timorj** [comment]
> App.axaml->Application.Resources `<x:Double x:Key="ControlContentThemeFontSize">12</x:Double>` `<FontFamily x:Key="ContentControlThemeFontFamily">Microsoft YaHei</FontFamily>`

Got it, it works fine. Thinks a lot, bro.

**Comment by rabbitism** [comment]
For anyone looking for Semi support of AvaloniaEdit, it is already available on nuget, not open source, but free to use. 

https://www.nuget.org/packages/Semi.Avalonia.AvaloniaEdit/11.2.0-beta2
