### ISSUE TITLE
Rendering problems on avalonia 0.6.1

### ISSUE THREAD

**Issue by vertexpipeline** [AvaloniaUI/AvaloniaEdit#52]
AvalonEdit  cannot render anything on 0.6.1 ver.
```html
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="IO" Height="300" xmlns:ae="clr-namespace:AvaloniaEdit;assembly=AvaloniaEdit"
  Width="400">
      <ae:TextEditor Background="Red" TextBlock.FontSize="12"/>
</Window>
```
![image](https://user-images.githubusercontent.com/26230414/38781126-b3afce86-4095-11e8-9d06-abb8fc5b324b.png)

**Comment by danwalmsley** [comment]
I will try have a quick look shortly.

**Comment by johannesegger** [comment]
This is really annoying, when did this stop working, i.e. what is the last good version of AvaloniaEdit and Avalonia where it works?

**Comment by danwalmsley** [comment]
master build is synced with avalonias nightly build.

We will make a release to match the next release of avalonia 0.7.

If you use nightly builds on avalonia it currently works.
