### ISSUE TITLE
Selection with mouse does not work

### ISSUE THREAD

**Issue by siegfriedpammer** [AvaloniaUI/AvaloniaEdit#57]
I am using the AvaloniaEdit 0.6.0 package.

I am using Avalonia with MVVM, and my XAML is this simple:

    <ae:TextEditor ShowLineNumbers="True" FontSize="14" FontFamily="Consolas" Document="{Binding SourceDocument}" SyntaxHighlighting="C#" />

When trying to select some text in the text view using the mouse, nothing happens. I cannot even place the caret using the mouse... Am I missing something? I would expect this to work out of the box.

**Comment by danwalmsley** [comment]
Set a background color, leaving it unset is transparent and mouse clicks go through transparent pixels.

**Comment by siegfriedpammer** [comment]
Thanks, for pointing this out. Was not obvious to me.
