### ISSUE TITLE
Help - What is the best way to "add a breakpoint"?

### ISSUE THREAD

**Issue by lock9** [AvaloniaUI/AvaloniaEdit#76]
Hello,
I would like to "add a visual breakpoint" in my file, but I don't know which classes to change. Is it possible to achieve this without changing the current code base? I want to be able to toggle a square/ball in the margins. 
I saw a code that would do something similar in the past, but I can't find it again.

Hints?

Thanks!

**Comment by aelij** [comment]
My guess is that using a custom Margin would work. But really, if you're building an IDE-like editor, you should take a look at [SharpDevelop](https://github.com/icsharpcode/SharpDevelop), where they use the original AvalonEdit for all of this stuff. I took quite a few ideas from there for RoslynPad.

**Comment by lock9** [comment]
Actually, this is an "intermediary project", the only thing is missing is the breakpoint, I am not looking for an "advanced IDE" at this time, we plan to do this using JS/Electron.
How can I add a custom Margin?
And thanks a lot for the quick response!

**Comment by aelij** [comment]
Search the code for `LineNumberMargin` in this repo and see how it's being used. As there are no docs, this is the best way to find info IMO. It's been a while since I worked on this project, so even I don't remember exactly how it's done :) I suggested SharpDevelop since you'd be able to find almost any IDE feature in their code.

**Comment by lock9** [comment]
It may be an option - I'm having another issue, the window is totally black in some MacOS computers :(

**Comment by danwalmsley** [comment]
https://github.com/VitalElement/AvalonStudio/blob/1774e1c3c849213772ccf972590bdf5451a8bb5f/AvalonStudio/AvalonStudio.Controls.Standard/CodeEditor/BreakPointMargin.cs
