### ISSUE TITLE
Visual glitch at the start of the line

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/AvaloniaEdit#8]
![line-bug](https://cloud.githubusercontent.com/assets/1067584/25363569/25f363c6-2964-11e7-9d64-c00eb5afa63a.gif)
Reproducible on Ubuntu + .NET Core.

**Comment by aelij** [comment]
How are those squares produced? Just by hitting <kbd>Enter</kbd>?

**Comment by kekekeks** [comment]
Yes, you need to hit Enter at the second level of indentation.

**Comment by aelij** [comment]
It probably has something to do with different line endings in Linux. I'll look into it, thanks.

Seems like indentation isn't working properly either.

**Comment by danwalmsley** [comment]
might be splitting /r/n up? You can use admin rights to accept the merge, its failing at publish stage, and needs my other pr to be finished to fixed.

**Comment by danwalmsley** [comment]
I think this is actually not rendering \t character on skiabackend

**Comment by danwalmsley** [comment]
The indentation strategy is inserting \t

**Comment by danipen** [comment]
Not reproduced in latest.
