### ISSUE TITLE
External links are unlinkable

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/AvaloniaEdit#83]
I've encountered such behavior in [AvaloniaILSpy](https://github.com/icsharpcode/AvaloniaILSpy) about field:

![AvaloniaILSpy about](https://user-images.githubusercontent.com/1150330/60389177-f28be500-9ac5-11e9-8e52-1718f39a7608.png)

**Comment by aelij** [comment]
I think it was resolved by #72. If there's an issue in ILSpy you should probably open an issue there.

**Comment by KvanTTT** [comment]
I've reproduced it in the latest master. Is #72 there?

**Comment by aelij** [comment]
You need to consume the event and launch a browser. AvaloniaEdit doesn't do this for you.

**Comment by aelij** [comment]
Closing for now. Feel free to reopen if the issues wasn't resolved.
