### ISSUE TITLE
Update Avalonia to 0.9.x

### ISSUE THREAD

**Issue by x2bool** [AvaloniaUI/AvaloniaEdit#85]
I know 0.9.x is not yet released but the changes seem to be more significant than the ones that could be fixed with the "find and replace version" approach. So I'll open this issue in advance.

**Comment by HendrikMennen** [comment]
#86

**Comment by KvanTTT** [comment]
I think we should wait for an official [NuGet release](https://www.nuget.org/packages/Avalonia/). But it's possible to update on **0.8.2**

**Comment by x2bool** [comment]
Thanks!
