### ISSUE TITLE
Update auto builds

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/AvaloniaEdit#98]
The latest nuget version is from October 15, 2019. The appveyor version is up to date but all demo artifacts are empty zip files. Sadly there is no way for developers to subscribe to appveyor builds.

There isn't too much activity on this repo. Can it be possible to auto update the nuget package on every commit? This is kind of useful when subscribed also to Avalonia releases (the current nuget package misses all the "Update avalonia" commits).

**Comment by danipen** [comment]
NuGet packages were updated: https://www.nuget.org/packages/Avalonia.AvaloniaEdit/
