### ISSUE TITLE
Cursor position for last line displays below last line when content requires scrolling

### ISSUE THREAD

**Issue by garyhertel** [AvaloniaUI/AvaloniaEdit#99]
If the scrollbar is active due to the content being larger than the text area, the text cursor shows an extra 30 pixels below where it should. This only happens when editing the last line too. Editing any other line works correctly.

Here's what the AvaloniaEdit.Demo shows
![image](https://user-images.githubusercontent.com/32446542/75635980-7eaf5880-5bcf-11ea-86cf-53af78f84b8b.png)

The problem is even worse for regular sized fonts too (size 16 here). Even editing the 2nd to last item has problems at this size. Note the sidebar doesn't even line up anymore.
![image](https://user-images.githubusercontent.com/32446542/75636057-4a886780-5bd0-11ea-8bc9-acceaf570fae.png)

**Comment by wutipong** [comment]
not really sure if this relates, but looks like it happens on the horizontal scroll as well.
![image](https://user-images.githubusercontent.com/3213191/100069301-2d38af00-2e6b-11eb-8b96-2bc0abbc5e3c.png)

The cursor is actually after the last character of the line, but it place far after that character.

**Comment by BAndysc** [comment]
It looks like this change to default settings: https://github.com/BAndysc/AvaloniaEdit/commit/4408d9fc7bdeece8f8ec9719ac3ed535e6837925 is kinda workaround for the problem, but horizontal caret issue still persists.
